### PR TITLE
Initial change for JDK8u152

### PR DESCRIPTION
**Pull request by przemelek**
We hava changes for Java8 build 152. 
We build and tests those changes on:
Windows for compressed product and fastdebug JDK1.8.0_152-x64 and JDK1.8.0_152-i586, for noncompressed product and fastdebug JDK1.8.0_152-x64
MacOS for compressed product and fastdebug JDK1.8.0_152-x64, the same for noncompressed
Linux for compressed product and fastdebug JDK1.8.0_152-x64 and JDK1.8.0_152-i586, for noncompressed product and fastdebug JDK1.8.0_152-x64.

Changes was done by pjbober (https://github.com/pjbober), for now I only restored CI in GW for this and build on all configurations above. In case of any questions I'm one who will answer.

### CODE REVIEW

**Comment by skybber** [comment]
Is the 8u152 not binary compatible with 8u144 ? Btw, what is problem now for us is the build for MacOS

**Comment by przemelek** [comment]
If you try to build base JVM 8u152 using changes for 8u144 it fails on each of systems (I think that on mutex.cpp or similar). So some changes were needed.

Not sure what you mean by problem with build for MacOS.
We were able to build for MacOS. We are building with:
Apple LLVM version 6.0 (clang-600.0.57) (based on LLVM 3.5svn)
Target: x86_64-apple-darwin13.4.0
Thread model: posix
On MacOS:
13.4.0 Darwin Kernel Version 13.4.0: Mon Jan 11 18:17:34 PST 2016; root:xnu-2422.115.15~1/RELEASE_X86_64 x86_64

**Comment by skybber** [comment]
Hi, currently we're able to build DCEVM for win and linux. We've lost opportunity to do it for Mac. If you could help us, you will be welcomed!

**Comment by przemelek** [comment]
We have DCEVM-Installer for build from my fork, and tomorrow (if everything will go well) we should have DCEVM-Installer build from this official repo of DCEVM.
As for now I don't have place on GW website to post it (it will be done latter, but this will take some time), any way to share it with you?
For MacOS builds we are using machine which was probably setup by @idubrov .

When/if we will work on DCEVM for Java 9, building should be easier on MacOS.

**Pull request merged**
